### ISSUE TITLE
BUG: players losing last equipped armor piece after death

### ISSUE THREAD

**Issue by n0ia96** [RandyKnapp/ValheimMods#377]
Only affect players connected to the server that aren't hosting the game.

After they die, they usually lose the last piece equipped

**Comment by NothingREM** [comment]
Same issue happened with me just now. Any information on how to get it back?

**Comment by madalkemyst** [comment]
Each time I die I lose anything in Z and V. Arrows, mostly. I have also lost the Hot Key overlay near the bottom of my screen.
thank you!

**Comment by AMurtagh** [comment]
Likely related, but I lost everything in my equipment inventory upon death IF my main inventory was full. Tested on a local game.

**Comment by AMurtagh** [comment]
Actually I can expand on that slightly. Mine clearly are not lost, but I just can't get to them somehow. See screenshot and you'll see one set of stuff (incl the replacement lvl 1 cloak) in my inventory, but in the upgrade window you can see TWO sets of everything incl. the original lvl 4 cloak (circled), but no idea how to get them back...

![image](https://user-images.githubusercontent.com/29312080/175772591-0b12aa45-55b0-4821-a904-28d22cad073f.png)

**Comment by RandyKnapp** [comment]
Hey folks, just out of curiosity, which of you are using Better Archery or any other mod that modifies inventory size?

**Comment by RandyKnapp** [comment]
I just uploaded a new version to the Nexus, can you all try it out?

**Comment by madalkemyst** [comment]
Yes, in the screen I posted I *was* using Better Archery. I found other issues with it besides the one connected t this mod. One so awful I lost my entire world.
We've started over from scratch with BA, and I am happy to report that the "lost arrows" are recovered upon death. They are no longer in the Z or V slots, it seems nothing is replaced into those slots (B is restored, no clue on that) but those items *are* in my inventory.
I do love BA, the few days I played with it were happy, however the other issues dictate I never use it again.
Was it a combination between your mod and BA? I have no idea. Is your mod more important to me? Yes. *oh, yes*
As for only my portion of this bug report, I'm taken care of. Others seems not so fixed. Good luck to the rest of you, truly.
Thanks Randy. I appreciate your quick time on this.

**Comment by hdeyeg** [comment]
Seems to still be an issue after lastest update, with people not being the host, Armor, misc + shortcuts is lost upon death. 
(ver 2.0.15) Sorry if its already been reported.

**Comment by dsge** [comment]
Yep, still can happen with 2.0.15 as it just happened to me. Everything that was equipped on my character or in my ZVB slots are gone after I picked up my corpse. 

This happened in singleplayer, no servers or other players involved. I did restart the game before picking up my corpse.

I'm not using Better Archery. I am using JotunnBackpacks 2.0.0 but I wasn't wearing a backpack on my character when I died (it was in my inventory though). I am also using NoSkillDrain 1.0.1 and SkillBasedCarryweight 1.0.0. I don't think I have anything else that seems to be related to inventory or death.

My full mod list with versions:
```
profileName: Default
mods:
  - name: denikson-BepInExPack_Valheim
    version:
      major: 5
      minor: 4
      patch: 1901
    enabled: true
  - name: Nextek-SpeedyPaths
    version:
      major: 1
      minor: 0
      patch: 6
    enabled: true
  - name: makail-ItemDrawers
    version:
      major: 0
      minor: 4
      patch: 4
    enabled: true
  - name: Tekla-JsonDotNet
    version:
      major: 13
      minor: 0
      patch: 1
    enabled: true
  - name: ValheimModding-Jotunn
    version:
      major: 2
      minor: 7
      patch: 6
    enabled: true
  - name: Tekla-ColorfulSigns
    version:
      major: 5
      minor: 4
      patch: 1604
    enabled: true
  - name: Advize-PlantEverything
    version:
      major: 1
      minor: 11
      patch: 5
    enabled: true
  - name: KaceCottam-TripleBronze
    version:
      major: 0
      minor: 2
      patch: 1
    enabled: true
  - name: swazrgb-Surtling_Boat
    version:
      major: 1
      minor: 0
      patch: 2
    enabled: true
  - name: ValheimModding-HookGenPatcher
    version:
      major: 0
      minor: 0
      patch: 3
    enabled: true
  - name: MathiasDecrock-SeedTotem
    version:
      major: 4
      minor: 2
      patch: 0
    enabled: true
  - name: RandyKnapp-ExtendedItemDataFramework
    version:
      major: 1
      minor: 0
      patch: 7
    enabled: true
  - name: EmrikNorth_and_Aedenthorn-JotunnBackpacks
    version:
      major: 2
      minor: 0
      patch: 0
    enabled: true
  - name: OhhLoz-HoneyPlus
    version:
      major: 2
      minor: 0
      patch: 2
    enabled: true
  - name: kassent-SkillBasedCarryweight
    version:
      major: 1
      minor: 0
      patch: 0
    enabled: true
  - name: FixItFelix-NoSkillDrain
    version:
      major: 1
      minor: 0
      patch: 1
    enabled: true
  - name: Advize-CartographySkill
    version:
      major: 2
      minor: 1
      patch: 0
    enabled: true
  - name: pipakin-SkillInjector
    version:
      major: 1
      minor: 1
      patch: 1
    enabled: true
  - name: thegreyham-CookingSkill
    version:
      major: 1
      minor: 2
      patch: 0
    enabled: true
  - name: RandyKnapp-EquipmentAndQuickSlots
    version:
      major: 2
      minor: 0
      patch: 15
    enabled: true
  - name: SpaceDrive-BlastFurnaceAllOres
    version:
      major: 1
      minor: 0
      patch: 1
    enabled: true
```
